### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by YiLiuHFUT** [RishabhMaheshwary/hard-label-attack#2]
When I use the command ：$ pip install -e . ".[dev]", the following error occurred:

ERROR: Cannot install textattack 0.2.15 (from E:\MyGit\learningcode\TextAttack) and textattack[dev]==0.2.15 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested textattack 0.2.15 (from E:\MyGit\learningcode\TextAttack)
    textattack[dev] 0.2.15 depends on textattack 0.2.15 (from E:\MyGit\learningcode\TextAttack)

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

I don't know what went wrong.

**Comment by RishabhMaheshwary** [comment]
Hi, Try with ```pip install -e .```, it should work.

**Comment by YiLiuHFUT** [comment]
> Hi, Try with `pip install -e .`, it should work.

Hello, my problem is solved, thank you very much for your answer!
